name: Build Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v3.1.0
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: bossett/wmp2mqtt:latest
